name: aggregated_collection
description: "A helper package for Firebase that aggregates documents to reduce Firebase read count"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  uuid: ^4.5.1
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0